import tkinter as tk
from tkinter import *
class profile_manage:
	def __init__(self,con,data):
		self.con=con
		self.con.query("select * from staff where(staffid='"+data+"');")
		self.data=self.con.store_result()
		self.data=self.data.fetch_row()
		self.head=tk.Toplevel()
		self.head.title(self.data[0][0])
		f=self.data[0][10]
		self.head.geometry("{}x{}".format(800,400))
		self.pic=PhotoImage(file=f)
		self.pic1=Label(self.head,image=self.pic)
		self.pic1.place(x=500,y=20)
		staffid=Label(self.head,text="StaffID :",font="Helvetical 15")
		staffid.place(x=10,y=10)
		staffid=Label(self.head,text=self.data[0][0],font="Helvetical 15")
		staffid.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		name=Label(self.head,text=self.data[0][1],font="Helvetical 15")
		name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		phone=Label(self.head,text=str(self.data[0][2]),font="Helvetical 15")
		phone.place(x=200,y=70)
		address=Label(self.head,text="Address :",font="Helvetical 15")
		address.place(x=10,y=100)
		address=Label(self.head,text=self.data[0][3],font="Helvetical 15")
		address.place(x=200,y=100)
		DOB=Label(self.head,text="DOB :",font="Helvetical 15")
		DOB.place(x=10,y=130)
		dob=Label(self.head,text=str(self.data[0][4]),font="Helvetical 15")
		dob.place(x=200,y=130)
		Email=Label(self.head,text="Email :",font="Helvetical 15")
		Email.place(x=10,y=160)
		Email=Label(self.head,text=self.data[0][5],font="Helvetical 15")
		Email.place(x=200,y=160)
		Salary=Label(self.head,text="Salary : ",font="Helvetical 15")
		Salary.place(x=10,y=190)
		salary=Label(self.head,text=str(self.data[0][6]),font="Helvetical 15")
		salary.place(x=200,y=190)
		des=Label(self.head,text="Designation :",font="Helvetical 15")
		des.place(x=10,y=220)
		des=Label(self.head,text=self.data[0][7],font="Helvetical 15")
		des.place(x=200,y=220)
		rep=Label(self.head,text="Reported :",font="Helvetical 15")
		rep.place(x=10,y=250)
		reports=Label(self.head,text=self.data[0][8],font="Helvetical 15")
		reports.place(x=200,y=250)
		room=Label(self.head,text="Room-No :",font="Helvetical 15")
		room.place(x=10,y=280)
		roomn=Label(self.head,text=self.data[0][9],font="Helvetical 15")
		roomn.place(x=200,y=280)
		self.head.mainloop()