import tkinter as tk
from tkinter import *
class detail:
	def __init__(self,con,data):
		self.con=con
		self.con.query("select * from student where(usn='"+data+"');")
		self.data=self.con.store_result()
		self.data=self.data.fetch_row()
		self.head=tk.Toplevel()
		self.head.title(self.data[0][0])
		f=self.data[0][9]
		self.head.geometry("{}x{}".format(800,600))
		self.pic=PhotoImage(file=f)
		self.pic1=Label(self.head,image=self.pic)
		self.pic1.place(x=500,y=20)
		usn=Label(self.head,text="USN :",font="Helvetical 15")
		usn.place(x=10,y=10)
		usn=Label(self.head,text=self.data[0][0],font="Helvetical 15")
		usn.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		name=Label(self.head,text=self.data[0][1],font="Helvetical 15")
		name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		phone=Label(self.head,text=str(self.data[0][2]),font="Helvetical 15")
		phone.place(x=200,y=70)
		address=Label(self.head,text="Address :",font="Helvetical 15")
		address.place(x=10,y=100)
		address=Label(self.head,text=self.data[0][3],font="Helvetical 15")
		address.place(x=200,y=100)
		DOB=Label(self.head,text="DOB :",font="Helvetical 15")
		DOB.place(x=10,y=130)
		dob=Label(self.head,text=str(self.data[0][4]),font="Helvetical 15")
		dob.place(x=200,y=130)
		sem=Label(self.head,text="Semester :",font="Helvetical 15")
		sem.place(x=10,y=160)
		sem=Label(self.head,text=self.data[0][5],font="Helvetical 15")
		sem.place(x=200,y=160)
		sec=Label(self.head,text="Section : ",font="Helvetical 15")
		sec.place(x=10,y=190)
		sec=Label(self.head,text=str(self.data[0][6]),font="Helvetical 15")
		sec.place(x=200,y=190)
		room=Label(self.head,text="Room :",font="Helvetical 15")
		room.place(x=10,y=220)
		room=Label(self.head,text=self.data[0][7],font="Helvetical 15")
		room.place(x=200,y=220)
		br=Label(self.head,text="Branch :",font="Helvetical 15")
		br.place(x=10,y=250)
		br=Label(self.head,text=self.data[0][8],font="Helvetical 15")
		br.place(x=200,y=250)
		fee=Label(self.head,text="Fee-Pending :",font="Helvetical 15")
		fee.place(x=10,y=280)
		rfee=Label(self.head,text=self.data[0][10],font="Helvetical 15")
		rfee.place(x=200,y=280)
		reported=Label(self.head,text="Reported-By :",font="Helvetical 15")
		reported.place(x=10,y=310)
		reported=Label(self.head,text=self.data[0][11],font="Helvetical 15")
		reported.place(x=200,y=310)
		pname=Label(self.head,text="Parent's Name :",font="Helvetical 15")
		pname.place(x=10,y=340)
		rpname=Label(self.head,text=self.data[0][12],font="Helvetical 15")
		rpname.place(x=200,y=340)
		pnum=Label(self.head,text="Parent's Phone :",font="Helvetical 15")
		pnum.place(x=10,y=370)
		rpnum=Label(self.head,text=self.data[0][13],font="Helvetical 15")
		rpnum.place(x=200,y=370)
		cin=Label(self.head,text="Check-In Time :",font="Helvetical 15")
		cin.place(x=10,y=400)
		rcin=Label(self.head,text=self.data[0][14],font="Helvetical 15")
		rcin.place(x=200,y=400)
		rcount=Label(self.head,text="Reported :",font="Helvetical 15")
		rcount.place(x=10,y=430)
		rocount=Label(self.head,text=self.data[0][15],font="Helvetical 15")
		rocount.place(x=200,y=430)
		atten=Label(self.head,text="Attendence :",font="Helvetical 15")
		atten.place(x=10,y=460)
		ratten=Label(self.head,text=self.data[0][16],font="Helvetical 15")
		ratten.place(x=200,y=460)
		visitor=Label(self.head,text="Visitors :",font="Helvetical 15")
		visitor.place(x=10,y=490)
		rvisitor=Label(self.head,text=self.data[0][17],font="Helvetical 15")
		rvisitor.place(x=200,y=490)
		self.head.mainloop()
class alter:
	def __init__(self,con,data):
		self.con=con
		self.con.query("select * from student where(usn='"+data+"');")
		self.data=self.con.store_result()
		self.data=self.data.fetch_row()
		self.head=tk.Toplevel()
		self.head.title(self.data[0][0])
		f=self.data[0][9]
		self.head.geometry("{}x{}".format(800,600))
		self.pic=PhotoImage(file=f)
		self.pic1=Label(self.head,image=self.pic)
		self.pic1.place(x=500,y=20)
		usn=Label(self.head,text="USN :",font="Helvetical 15")
		usn.place(x=10,y=10)
		self.usn=Label(self.head,text=data,font="Helvetical 15")
		self.usn.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		self.name=Entry(self.head)
		self.name.insert(0,self.data[0][1])
		self.name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		self.phone=Entry(self.head)
		self.phone.insert(0,self.data[0][2])
		self.phone.place(x=200,y=70)
		address=Label(self.head,text="Address :",font="Helvetical 15")
		address.place(x=10,y=100)
		self.address=Entry(self.head)
		self.address.insert(0,self.data[0][3])
		self.address.place(x=200,y=100)
		DOB=Label(self.head,text="DOB :",font="Helvetical 15")
		DOB.place(x=10,y=130)
		self.dob=Entry(self.head)
		self.dob.insert(0,self.data[0][4])
		self.dob.place(x=200,y=130)
		sem=Label(self.head,text="Semester :",font="Helvetical 15")
		sem.place(x=10,y=160)
		self.sem=Entry(self.head)
		self.sem.insert(0,self.data[0][5])
		self.sem.place(x=200,y=160)
		sec=Label(self.head,text="Section : ",font="Helvetical 15")
		sec.place(x=10,y=190)
		self.sec=Entry(self.head)
		self.sec.insert(0,self.data[0][6])
		self.sec.place(x=200,y=190)
		room=Label(self.head,text="Room :",font="Helvetical 15")
		room.place(x=10,y=220)
		self.room=Entry(self.head)
		self.room.insert(0,self.data[0][7])
		self.room.place(x=200,y=220)
		br=Label(self.head,text="Branch :",font="Helvetical 15")
		br.place(x=10,y=250)
		self.br=Entry(self.head)
		self.br.insert(0,self.data[0][8])
		self.br.place(x=200,y=250)
		fee=Label(self.head,text="Fee-Pending :",font="Helvetical 15")
		fee.place(x=10,y=280)
		self.rfee=Entry(self.head)
		self.rfee.insert(0,self.data[0][10])
		self.rfee.place(x=200,y=280)
		reported=Label(self.head,text="Reported-By :",font="Helvetical 15")
		reported.place(x=10,y=310)
		self.reported=Label(self.head,text=self.data[0][11])
		self.reported.place(x=200,y=310)
		pname=Label(self.head,text="Parent's Name :",font="Helvetical 15")
		pname.place(x=10,y=340)
		self.rpname=Entry(self.head)
		self.rpname.insert(0,self.data[0][12])
		self.rpname.place(x=200,y=340)
		pnum=Label(self.head,text="Parent's Phone :",font="Helvetical 15")
		pnum.place(x=10,y=370)
		self.rpnum=Entry(self.head)
		self.rpnum.insert(0,self.data[0][13])
		self.rpnum.place(x=200,y=370)
		cin=Label(self.head,text="Check-In Time :",font="Helvetical 15")
		cin.place(x=10,y=400)
		self.rcin=Entry(self.head)
		self.rcin.insert(0,self.data[0][14])
		self.rcin.place(x=200,y=400)
		rcount=Label(self.head,text="Reported :",font="Helvetical 15")
		rcount.place(x=10,y=430)
		self.rocount=Entry(self.head)
		self.rocount.insert(0,self.data[0][15])
		self.rocount.place(x=200,y=430)
		atten=Label(self.head,text="Attendence :",font="Helvetical 15")
		atten.place(x=10,y=460)
		self.atten=Entry(self.head)
		self.atten.insert(0,self.data[0][16])
		self.atten.place(x=200,y=460)
		visitor=Label(self.head,text="Visitors :",font="Helvetical 15")
		visitor.place(x=10,y=490)
		self.visitor=Label(self.head,text=self.data[0][17],font="Helvetical 15")
		self.visitor.place(x=200,y=490)
		pic=Label(self.head,text="Pic Url :",font="Helvetical 15")
		pic.place(x=10,y=520)
		self.pic=Entry(self.head)
		self.pic.insert(0,self.data[0][9])
		self.pic.place(x=200,y=520)
		submit=Button(self.head,text="Submit",command=self.action)
		submit.place(x=200,y=550)
		self.head.mainloop()
	def action(self):
		
		self.name=self.name.get()
		self.phone=self.phone.get()
		self.address=self.address.get()
		self.dob=self.dob.get()
		self.sem=self.sem.get()
		self.sec=self.sec.get()
		self.room=self.room.get()
		self.br=self.br.get()
		self.rfee=self.rfee.get()
		self.rpname=self.rpname.get()
		self.rpnum=self.rpnum.get()
		self.rcin=self.rcin.get()
		self.rocount=self.rocount.get()
		self.atten=self.atten.get()
		self.pic=self.pic.get()
		self.head.destroy()
		self.con.query("update student set name='"+self.name+"', phont="+str(self.phone)+",address='"+self.address+"',dob='"+str(self.dob)+"',sem="+str(self.sem)+", sec='"+self.sec+"', room="+str(self.room)+", branch='"+self.br+"',pic='"+self.pic+"',fee_pending="+str(self.rfee)+",parent_name='"+self.rpname+"',parent_phone="+str(self.rpnum)+",check_in='"+self.rcin+"',reported="+str(self.rocount)+",attendance="+str(self.atten)+" where(usn='"+self.data[0][0]+"');")
		self.con.commit()
		self.head=tk.Tk()
		self.head.title("Success")
		self.head.geometry("{}x{}".format(150,150))
		x=Label(self.head,text="Data Altered Successfully")
		x.place(x=10,y=20)
		self.head.mainloop()
class remove:
	def __init__(self,con,data):
		self.con=con
		self.con.query("delete from student where(usn='"+data+"');")
		self.con.commit()
		self.con.query("delete from fine where(usn='"+data+"');")
		self.con.commit()
		self.con.query("delete from visitor where(usn='"+data+"');")
		self.con.commit()
		self.head=tk.Tk()
		self.head.title("Success")
		self.head.geometry("{}x{}".format(250,150))
		x=Label(self.head,text="Record Deleted Successfully")
		x.place(x=10,y=20)
		self.head.mainloop()
class add:
	def __init__(self,con):
		self.con=con
		self.head=tk.Toplevel()
		self.head.title("Add Student")
		self.head.geometry("{}x{}".format(600,600))
		usn=Label(self.head,text="USN :",font="Helvetical 15")
		usn.place(x=10,y=10)
		self.usn1=Entry(self.head)
		self.usn1.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		self.name=Entry(self.head)
		self.name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		self.phone=Entry(self.head)
		self.phone.place(x=200,y=70)
		address=Label(self.head,text="Address :",font="Helvetical 15")
		address.place(x=10,y=100)
		self.address=Entry(self.head)
		self.address.place(x=200,y=100)
		DOB=Label(self.head,text="DOB :",font="Helvetical 15")
		DOB.place(x=10,y=130)
		self.dob=Entry(self.head)
		self.dob.place(x=200,y=130)
		sem=Label(self.head,text="Semester :",font="Helvetical 15")
		sem.place(x=10,y=160)
		self.sem=Entry(self.head)
		self.sem.place(x=200,y=160)
		sec=Label(self.head,text="Section : ",font="Helvetical 15")
		sec.place(x=10,y=190)
		self.sec=Entry(self.head)
		self.sec.place(x=200,y=190)
		room=Label(self.head,text="Room :",font="Helvetical 15")
		room.place(x=10,y=220)
		self.room=Entry(self.head)
		self.room.place(x=200,y=220)
		br=Label(self.head,text="Branch :",font="Helvetical 15")
		br.place(x=10,y=250)
		self.br=Entry(self.head)
		self.br.place(x=200,y=250)
		fee=Label(self.head,text="Fee-Pending :",font="Helvetical 15")
		fee.place(x=10,y=280)
		self.rfee=Entry(self.head)
		self.rfee.place(x=200,y=280)
		pname=Label(self.head,text="Parent's Name :",font="Helvetical 15")
		pname.place(x=10,y=310)
		self.rpname=Entry(self.head)
		self.rpname.place(x=200,y=310)
		pnum=Label(self.head,text="Parent's Phone :",font="Helvetical 15")
		pnum.place(x=10,y=340)
		self.rpnum=Entry(self.head)
		self.rpnum.place(x=200,y=340)
		cin=Label(self.head,text="Check-In Time :",font="Helvetical 15")
		cin.place(x=10,y=370)
		self.rcin=Entry(self.head)
		self.rcin.place(x=200,y=370)
		atten=Label(self.head,text="Attendence :",font="Helvetical 15")
		atten.place(x=10,y=400)
		self.atten=Entry(self.head)
		self.atten.place(x=200,y=400)
		pic=Label(self.head,text="Pic Url :",font="Helvetical 15")
		pic.place(x=10,y=430)
		self.pic=Entry(self.head)
		self.pic.place(x=200,y=430)
		submit=Button(self.head,text="Submit",command=self.action)
		submit.place(x=200,y=490)
		submit=Button(self.head,text="Cancel",command=self.head.destroy)
		submit.place(x=300,y=490)
		self.head.mainloop()
	def action(self):
		self.usn1=self.usn1.get()
		self.name=self.name.get()
		self.phone=self.phone.get()
		self.address=self.address.get()
		self.dob=self.dob.get()
		self.sem=self.sem.get()
		self.sec=self.sec.get()
		self.room=self.room.get()
		self.br=self.br.get()
		self.rfee=self.rfee.get()
		self.rpname=self.rpname.get()
		self.rpnum=self.rpnum.get()
		self.rcin=self.rcin.get()
		self.atten=self.atten.get()
		self.pic=self.pic.get()
		if(self.usn1 and self.name and self.phone and self.address and self.dob and self.sem and self.sec and self.room and self.br and self.rfee and self.rpname and self.rpnum and self.rcin and self.atten and self.pic):
			self.con.query("insert into student(usn,name,phont,address,dob,sem,sec,room,branch,pic,fee_pending,parent_name,parent_phone,check_in,reported,attendance,visitor_count) values('"+self.usn1+"','"+self.name+"',"+str(self.phone)+",'"+self.address+"','"+self.dob+"',"+str(self.sem)+",'"+self.sec+"',"+str(self.room)+",'"+self.br+"','"+self.pic+"',"+str(self.rfee)+",'"+self.rpname+"',"+self.rpnum+",'"+self.rcin+"',0,"+str(self.atten)+",0);")
			self.con.commit()
			self.head1=tk.Tk()
			self.head1.title("Success")
			self.head1.geometry("{}x{}".format(200,150))
			x=Label(self.head1,text="Student Added Successfully")
			x.place(x=10,y=20)
			self.head1.mainloop()
		else:
			self.head1=tk.Tk()
			self.head1.title("Error")
			self.head1.geometry("{}x{}".format(150,150))
			x=Label(self.head1,text="Data Missing")
			x.place(x=10,y=20)
			self.head1.mainloop()
class fees:
	def __init__(self,con,data):
		self.con=con
		self.data=data
		self.con.query("select fee_pending from student where(usn='"+self.data+"');")
		self.data=self.con.store_result()
		self.data=self.data.fetch_row()
		self.head1=tk.Tk()
		res="Fee Pending:    "+str(self.data[0][0])
		self.head1.title("Fee Status")
		self.head1.geometry("{}x{}".format(400,200))
		x=Label(self.head1,text=res,font="Helvetical 15")
		x.place(x=10,y=20)
		self.head1.mainloop()

class fine:
	def __init__(self,con,data):
		self.con=con
		self.count=0
		self.con.query("select usn,name,sem,sec,room,branch,fee_pending,pic from student where(usn='"+data+"');")
		self.data=self.con.store_result()
		self.data=self.data.fetch_row()
		self.con.query("select * from fine where(usn='"+data+"');")
		self.data_none=self.con.store_result()
		self.data1=self.data_none.fetch_row()
		i=self.data1
		while(i):
			i=self.data_none.fetch_row()
			if(i):
				self.data1=i
				self.count+=1
		self.head=tk.Toplevel()
		self.head.title(self.data[0][0])
		f=self.data[0][7]
		self.head.geometry("{}x{}".format(800,600))
		self.pic=PhotoImage(file=f)
		self.pic1=Label(self.head,image=self.pic)
		self.pic1.place(x=500,y=20)
		usn=Label(self.head,text="USN :",font="Helvetical 15")
		usn.place(x=10,y=10)
		usn=Label(self.head,text=self.data[0][0],font="Helvetical 15")
		usn.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		name=Label(self.head,text=self.data[0][1],font="Helvetical 15")
		name.place(x=200,y=40)
		sem=Label(self.head,text="Semester :",font="Helvetical 15")
		sem.place(x=10,y=70)
		sem=Label(self.head,text=self.data[0][2],font="Helvetical 15")
		sem.place(x=200,y=70)
		sec=Label(self.head,text="Section : ",font="Helvetical 15")
		sec.place(x=10,y=100)
		sec=Label(self.head,text=str(self.data[0][3]),font="Helvetical 15")
		sec.place(x=200,y=100)
		room=Label(self.head,text="Room :",font="Helvetical 15")
		room.place(x=10,y=130)
		room=Label(self.head,text=self.data[0][4],font="Helvetical 15")
		room.place(x=200,y=130)
		br=Label(self.head,text="Branch :",font="Helvetical 15")
		br.place(x=10,y=160)
		br=Label(self.head,text=self.data[0][5],font="Helvetical 15")
		br.place(x=200,y=160)
		fee=Label(self.head,text="Fee-Pending :",font="Helvetical 15")
		fee.place(x=10,y=190)
		rfee=Label(self.head,text=self.data[0][6],font="Helvetical 15")
		rfee.place(x=200,y=190)
		fine=Label(self.head,text="Fine Amount :",font="Helvetical 15")
		fine.place(x=10,y=220)
		try:
			fine=Label(self.head,text=self.data1[0][2],font="Helvetical 15")
			fine.place(x=200,y=220)
			d=Label(self.head,text="Date-Of-Pay :",font="Helvetical 15")
			d.place(x=10,y=250)
			d=Label(self.head,text=self.data1[0][1],font="Helvetical 15")
			d.place(x=200,y=250)
			c=Label(self.head,text="Cause :",font="Helvetical 15")
			c.place(x=10,y=280)
			c=Label(self.head,text=self.data1[0][3],font="Helvetical 15")
			c.place(x=200,y=280)
		except:
			fine=Label(self.head,text="No Fine Imposed",font="Helvetical 15")
			fine.place(x=200,y=220)
		v=Label(self.head,text="Number of times fine Paid :",font="Helvetical 15")
		v.place(x=10,y=310)
		v=Label(self.head,text=self.count+1,font="Helvetical 15")
		v.place(x=300,y=310)
		self.head.mainloop()
class report:
	def __init__(self,con,data,staff):
		self.staff=staff
		self.con=con
		self.con.query("select reported from student where(usn='"+data+"');")	
		q=self.con.store_result()
		q=q.fetch_row()
		q=q[0][0]+1
		self.con.query("update student set reported="+str(q)+", reported_by='"+self.staff+"' where(usn='"+data+"');")
		self.con.commit()
		self.con.query("select reported from staff where(staffid='"+self.staff+"');")
		q=self.con.store_result()
		q=q.fetch_row()
		q=q[0][0]+1
		self.con.query("update staff set reported="+str(q)+" where(staffid='"+self.staff+"');")
		self.con.commit()
		self.head1=tk.Tk()
		self.head1.title("Success")
		self.head1.geometry("{}x{}".format(200,150))
		x=Label(self.head1,text="Student Reported Successfully")
		x.place(x=10,y=20)
		self.head1.mainloop()
class collect_fine:
	def __init__(self,con,data):
		self.con=con
		self.usn1=data
		self.head=tk.Tk()
		self.head.geometry("{}x{}".format(400,400))
		self.head.title("Fine Collection")
		usn=Label(self.head,text="USN :",font="Helvetical 15")
		usn.place(x=10,y=10)
		self.usn=Label(self.head,text=data,font="Helvetical 15")
		self.usn.place(x=200,y=10)
		Amount=Label(self.head,text="Amount :",font="Helvetical 15")
		Amount.place(x=10,y=40)
		self.Amount=Entry(self.head)
		self.Amount.place(x=200,y=40)
		Cause=Label(self.head,text="Cause :",font="Helvetical 15")
		Cause.place(x=10,y=70)
		self.Cause=Entry(self.head)
		self.Cause.place(x=200,y=70)
		d=Label(self.head,text="Date of pay :",font="Helvetical 15")
		d.place(x=10,y=100)
		self.d=Entry(self.head)
		self.d.place(x=200,y=100)
		x=Button(self.head,text="Submit",command=self.action)
		x.place(x=200,y=140)
	def action(self):
		self.Amount=self.Amount.get()
		self.Cause=self.Cause.get()
		self.d=self.d.get()
		self.head.destroy()
		self.con.query("insert into fine values('"+self.usn1+"','"+self.d+"',"+str(self.Amount)+",'"+self.Cause+"');")
		self.con.commit()
		self.head1=tk.Tk()
		self.head1.title("Success")
		self.head1.geometry("{}x{}".format(200,150))
		x=Label(self.head1,text="Fine Collected Successfully")
		x.place(x=10,y=20)
		self.head1.mainloop()
class add_visitor:
	def __init__(self,con,data):
		self.con=con
		self.usn1=data
		self.head=tk.Tk()
		self.head.geometry("{}x{}".format(400,400))
		self.head.title("Add Visitor")
		usn=Label(self.head,text="USN:",font="Helvetical 15")
		usn.place(x=10,y=10)
		self.usn=Label(self.head,text=data,font="Helvetical 15")
		self.usn.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		self.name=Entry(self.head)
		self.name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		self.phone=Entry(self.head)
		self.phone.place(x=200,y=70)
		Address=Label(self.head,text="Address :",font="Helvetical 15")
		Address.place(x=10,y=100)
		self.Address=Entry(self.head)
		self.Address.place(x=200,y=100)
		d1=Label(self.head,text="Check-In Date :",font="Helvetical 15")
		d1.place(x=10,y=130)
		self.d1=Entry(self.head)
		self.d1.place(x=200,y=130)
		d2=Label(self.head,text="Check-Out Date :",font="Helvetical 15")
		d2.place(x=10,y=160)
		self.d2=Entry(self.head)
		self.d2.place(x=200,y=160)
		x=Button(self.head,text="Submit",command=self.action)
		x.place(x=200,y=200)
	def action(self):
		self.name=self.name.get()
		self.Address=self.Address.get()
		self.phone=self.phone.get()
		self.d1=self.d1.get()
		self.d2=self.d2.get()
		self.head.destroy()
		self.con.query("insert into visitor values('"+self.usn1+"','"+self.name+"',"+str(self.phone)+",'"+self.Address+"','"+str(self.d1)+"','"+str(self.d2)+"');")
		self.con.commit()
		self.con.query("select visitor_count from student where(usn='"+self.usn1+"');")
		q=self.con.store_result()
		q=q.fetch_row()
		q=q[0][0]+1
		self.con.query("update student set visitor_count="+str(q)+" where(usn='"+self.usn1+"');")
		self.con.commit()
		self.head1=tk.Tk()
		self.head1.title("Success")
		self.head1.geometry("{}x{}".format(200,150))
		x=Label(self.head1,text="Visitor added Successfully")
		x.place(x=10,y=20)
		self.head1.mainloop()
class vis_detail:
	def __init__(self,con,data):
		self.con=con
		self.con.query("select count(*) from visitor where(usn='"+data+"');")
		self.count=self.con.store_result()
		self.count=self.count.fetch_row()
		self.con.query("select * from visitor where(usn='"+data+"');")
		res=self.con.store_result()
		data1=res.fetch_row()
		i=data1
		while(i):
			i=res.fetch_row()
			if(i):
				data1=i
		self.head=tk.Tk()
		self.head.geometry("{}x{}".format(400,400))
		self.head.title("Visitor Details")
		usn=Label(self.head,text="USN:",font="Helvetical 15")
		usn.place(x=10,y=10)
		self.usn=Label(self.head,text=data,font="Helvetical 15")
		self.usn.place(x=200,y=10)
		name=Label(self.head,text="Name :",font="Helvetical 15")
		name.place(x=10,y=40)
		self.name=Label(self.head,text=data1[0][1],font="Helvetical 15")
		self.name.place(x=200,y=40)
		phone=Label(self.head,text="Phone :",font="Helvetical 15")
		phone.place(x=10,y=70)
		self.phone=Label(self.head,text=data1[0][2],font="Helvetical 15")
		self.phone.place(x=200,y=70)
		Address=Label(self.head,text="Address :",font="Helvetical 15")
		Address.place(x=10,y=100)
		self.Address=Label(self.head,text=data1[0][3],font="Helvetical 15")
		self.Address.place(x=200,y=100)
		d1=Label(self.head,text="Check-In Date :",font="Helvetical 15")
		d1.place(x=10,y=130)
		self.d1=Label(self.head,text=data1[0][4],font="Helvetical 15")
		self.d1.place(x=200,y=130)
		d2=Label(self.head,text="Check-Out Date :",font="Helvetical 15")
		d2.place(x=10,y=160)
		self.d2=Label(self.head,text=data1[0][5],font="Helvetical 15")
		self.d2.place(x=200,y=160)
		v=Label(self.head,text="Number of Visitors :",font="Helvetical 15")
		v.place(x=10,y=190)
		v=Label(self.head,text=self.count[0][0],font="Helvetical 15")
		v.place(x=300,y=190)
		x=Button(self.head,text="Close",command=self.head.destroy)
		x.place(x=200,y=230)
		self.head.mainloop()